### ISSUE TITLE
500: Gateway translation

### ISSUE THREAD

**Issue by peyronth** [Dative-GPI/foundation-extension#20]
![image](https://github.com/Dative-GPI/foundation-template/assets/76468954/c963cd9d-e6f5-4353-a817-e7383a4afdfe)

FULL LOG
=======
`System.ArgumentException: IDX12709: CanReadToken() returned false. JWT is not well formed: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ReadJwtToken(String token)
   at Foundation.Template.Gateway.Middlewares.JWTAuthenticationMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json, text/plain, */*
Host: extension.localhost
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: null
Authorization: Bearer null
Cache-Control: no-cache
Pragma: no-cache
Referer: https://extension.localhost/organisations/41ea29a1-bbfe-4f4a-86b3-425963471053/controls/actiongroups/fdf6273f-b405-4122-ad43-eb624254bb94
Priority: u=1, i
Sec-Ch-Ua: "Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
X-Forwarded-For: 172.21.0.1
X-Forwarded-Host: extension.localhost
X-Forwarded-Port: 443
X-Forwarded-Server: aba2edb825aa
X-Real-Ip: 172.21.0.1
X-Original-Proto: http`

**Comment by peyronth** [comment]
Working after refreshing page : 
![image](https://github.com/Dative-GPI/foundation-template/assets/76468954/7c086e7a-7b47-4689-99e5-cb2e5bceb522)
